### PR TITLE
Improvement replace values strategy

### PR DESCRIPTION
**Pull request by sdrees**
#### What does it implement/fix? Explain your changes.
The function replace_value has a third strategy defining value that is per default causing inplace changes, but can be used via copy.copy or copy.deepcopy to work on shallow or deep clones of the parameter dict where the replacement should take place.

As small optimzation for small and large dicts the value dictview object is used as a filter before iterating ofer the keys.

#### Where has this been tested?
Python Version: 3.6.4
Operating System: darwin 10.12.6

#### Does this close any currently open issues? 

* Requested documentation snippet, 
* a small enhancement in utils, 
* less clumsy code in core.fuzzer and core.checker, 
* more flexible.

#### Does this add any new dependency?
No.

#### Does this add any new command line switch/option?
No.

#### Any other comments you would like to make?
Well, I created tests, but I wait on what testing strategy the repository owner would like to follow 😄 

#### Some Questions
- [x] I have documented my code.
- [x] I have tested my build before submitting the pull request.

### CODE REVIEW

**Comment by sdrees** [comment]
Changed target branch to dev (this change here works equally well wth master, but the upstream selenium etc. dependencies seem to prohibit that for now). Hope it helps, Stefan.

**Comment by sdrees** [comment]
Please advice what I should do, to ease integration (changing the target branch from master to dev in the pull request did not retriever the travis-ci check (which failed do to a missing selenium dependency I understand).

**Comment by s0md3v** [comment]
Can you change the branch back to `master`?
Because the `dev` branch requires a lot of work to be production ready so we can definitely merge your fork before that.

**Comment by sdrees** [comment]
Changed back to master as target, thanks for the fast advice.

**Comment by s0md3v** [comment]
It's neat!

**Comment by s0md3v** [comment]
I guess we will need to change `replace_value` to `replaceValue` since camel case is followed throughout the program.

**Comment by s0md3v** [comment]
Thanks for contributing :heart:

**Pull request merged**
