### PR TITLE
Pure python2.7 compatibility

### PR DESCRIPTION
**Pull request by jaywon**
See  full details commit history but there were issues in installation with the mixture of Python3 and Python2.7 libraries/environment so I refactored to be dependent on Python2.7 only due to the hard requirement of the `mechanize` library which would need to be replaced for Python3 compatibility.

Awesome tool, hope this helps! 🎈

### CODE REVIEW

**Comment by jaywon** [comment]
Will resolve #41 if accepted. 😃

**Comment by s0md3v** [comment]
I am sorry but I tried to drop Python 2 support in the latest release so I can't merge this one.
Sorry again and thanks for your contribution.

**Comment by jaywon** [comment]
All about moving forward with Python3, the problem is that the `mechanize` module is *only* supported in Python2.7 so it's not a full Python3 compliant. You still must have Python2.7 installed on the system and it makes it difficult to virtualize the environment. 

I guess I could be more helpful by looking at what `mechanize` is doing and trying to come up with an alternate solution?

Release today looks great btw, great refactor!

**Comment by s0md3v** [comment]
I know and I replaced mechanize with requests already ;)

**Pull request closed without merging**
