### PR TITLE
Improved and documented some util functions

### PR DESCRIPTION
**Pull request by sdrees**
#### Where has this been tested?
Python Version: 3.6.4
Operating System: macOS Sierra 10.12.6 (16G1618)

#### Does this close any currently open issues? 
Well, it tries to support in documentation and enhancing code base

#### Does this add any new dependency?
No

#### Does this add any new command line switch/option?
No

#### Any other comments you would like to make?
One function `flattenParams` is unused, so I refactored it into `flattenAndPatch` with switched and renamed arguments.

#### Some Questions
- [x ] I have documented my code.
- [ x] I have tested my build before submitting the pull request.

### CODE REVIEW

**Comment by s0md3v** [comment]
1. Revert variable name changes in `genGen` function.
2. Remove notes that you have added, they aren't helpful to other developers
3. We remove `flattenParams`

**Comment by sdrees** [comment]
> 1. Revert variable name changes in `genGen` function.
> 2. Remove notes that you have added, they aren't helpful to other developers
> 3. We can remove `flattenParams`

Two questions w.r.t. the review feedback above:
1. Does (1) also include `aFunction` (because `function` might be surprising when defining later a local function inside `genGen` during further refactoring
2. Can You maybe provide me info on what the many parameters of `genGen` stand for, so that the docstring will be helpful to other developers?

Thanks,
Stefan

**Comment by s0md3v** [comment]
- **fillings**: Strings that can be used instead of space
- **eFillings**: Characters that can be used between = and JavaScript function or event handler [`<svg onload<eFilling>=<eFilling>function()>`]
- **lfillings**: Characters that can be used exactly before `>` in a HTML tag.
- **eventHandlers**: Event handlers and the tags compatible with them to be used while generating payloads
- **tags**: HTML tags to be used while generating payloads.
- **functions**: JavaScript popup functions e.g. `alert()` or `confirm()`
- **ends**: Strings to end a HTML tag  [`>` or `//`]
- **breaker**: String needed to break out of the context
- **special**: The HTML tag which contains the reflection i.e. user input

**Comment by sdrees** [comment]
There you go :smile:

**Comment by s0md3v** [comment]
Hi @sdrees ,

I was thinking that we should document all the functions and merge it in one go.
A lot of commits can be irritating to the watchers.

**Comment by sdrees** [comment]
Ok, then I will go ahead for `core.utils` amending my branch and you merge when you think it is good.

**Comment by nemoload** [comment]
I hope you add support for type hints alongside the documentation.
See: https://docs.python.org/3/library/typing.html

**Comment by s0md3v** [comment]
Closing due to inactivity, can be re-opened.

**Pull request closed without merging**
