### PR TITLE
Use environment variables instead of hardcoded editor

### PR DESCRIPTION
**Pull request by cym13**
Increases portability, reduces surprise.

### CODE REVIEW

**Comment by s0md3v** [comment]
Am I missing something here?
```
~> python3
Python 3.6.7 (default, Oct 21 2018, 08:08:16) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.get("LANG")
'en_IN'
>>> os.environ.get("EDITOR")
>>> 
```

**Comment by cym13** [comment]
This just means you didn't define that environment variable. Since very many programs take it into account I can only advise you to define it, and take it into account yourself. Using a hardcoded reference to nano (which may very well not be present) just isn't the way to go IMHO.

**Comment by cym13** [comment]
If you mean that it should be a global variable I disagree, using EDITOR is really the standard UNIX way. It's not something that, as a user, you want to define on a program-by-program basis, that behaviour corresponds to environment variables, and all programs really (web browsers, mail clients, package managers...) do it that way. It's what contains the least element of surprise.

**Comment by s0md3v** [comment]
Makes sense. Let's keep it both ways, we will use the "EDITOR" environment variable and if it's not available, we will use the one defined in `config.py`.

**Comment by cym13** [comment]
Looks good to me :)

**Comment by s0md3v** [comment]
Can we merge it now?

**Pull request merged**
