### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by pyneda**
The exception below is raised when no cookies are supplied and post method is not used:
```
Traceback (most recent call last):
  File "xsstrike", line 256, in <module>
    main() #This is the true start of the program
  File "xsstrike", line 249, in main
    initiator(target, method)
TypeError: initiator() missing 1 required positional argument: 'cookie'
```
Fixed by setting default initiator cookie parameter value as None.

### CODE REVIEW

**Comment by s0md3v** [comment]
"post method is not used"??
Do you mean when get method is used?

**Comment by pyneda** [comment]
Yes, sorry if I was not clear enough. You can see required input below.
```
[?] Enter a url: https://example.com
[?] Enter cookie (if any): 
[?] Does it use POST method? [Y/n] n
```

**Comment by pyneda** [comment]
Yes, and sorry if explaination was not clear enough. Btw, just seen that the issue is also raised when cookie is supplied so have changed the approach and added the cookie as an initiator method parameter instead of allowing it as None.

**Comment by s0md3v** [comment]
I verified the bug as well as the patch.
Thanks for the contribution ^_^

**Pull request merged**
