### PR TITLE
improve WAF detection methods

### PR DESCRIPTION
**Pull request by rubyman**
Hi!

Some method to check for WAF without sending any payload.also detect WAFs like Fortiweb that cannot be detected with payload.

Thank you

### CODE REVIEW

**Comment by rubyman** [comment]
Your welcome!

But some WAFs like Fortiweb in payload included requests leave nothing(when WAF detect malicious behavior). but when you request a page like a normal user WAF leave cookie.

**Comment by s0md3v** [comment]
Fair enough.

Well if that's the case then I believe instead of  making a new request, we can supply [this response](https://github.com/s0md3v/XSStrike/blob/b490ab26b9cdcbfd4c0e89b302ce9881650c1174/xsstrike.py#L123) to your newly added function.

https://github.com/s0md3v/XSStrike/blob/b490ab26b9cdcbfd4c0e89b302ce9881650c1174/xsstrike.py#L123

**Comment by rubyman** [comment]
you did not pass Params?

**Comment by s0md3v** [comment]
I don't think not issuing them will make the WAF think it's a malicious request.

**Comment by s0md3v** [comment]
We can issue them tho, not a problem,

**Comment by s0md3v** [comment]
Sorry bruh,

To support a wider range of WAFs and to make it easy to add new signatures or modify the existing ones, I rewrote `wafDetector.py` and now it loads signatures from `/db/wafSignatures.json` which contains signatures of up to 66 WAFs.

I am sorry that you wrote all that code and we can't merge it now.
Also, we shouldn't really send another request without a malicious payloads to trigger some rare WAFs now.
As the Zen of Python puts it, `Special cases aren't special enough to break the rules`

**Comment by rubyman** [comment]
OK, no problrm

**Pull request closed without merging**
