### PR TITLE
added SOCKS5 proxy support

### PR DESCRIPTION
**Pull request by ZigmundVonZaun**
Added SOCKS5 proxy support
added standard Python .gitignore file
updated README.md to reflect changes

### CODE REVIEW

**Comment by s0md3v** [comment]
Hi there,
Thanks a lot for contributing.
But if you can make it compatible HTTP proxies that would be even better.
Thanks again.

**Comment by ZigmundVonZaun** [comment]
It supports HTTP proxies as is. I just tested. The reason I didn't earlier is because the free proxies out there are mostly unreliable. Ill update the README.md and prompts to reflect this

**Comment by s0md3v** [comment]
I installed the dependencies for socks support but it doesn't seem to work.
I tried many socks5/http(s) proxies but they end up causing XSStrike to hang at the cookie prompt.
Have you tested your fork properly?

**Comment by ZigmundVonZaun** [comment]
it hangs because free proxies are not reliable, they time out a lot. And yes I tested it with different proxies and it worked. Why would I make a pull request of something that doesnt work?

bildschirmfoto zu 2018-06-17 19-58-33

**Comment by ZigmundVonZaun** [comment]
Test with this

```python
import requests

session = requests.session()

proxies = ["socks5h://localhost:9050", "http://80.211.154.220:8888", "https://80.211.28.56:80"]

for proxy in proxies:

    session.proxies['https'] = proxy

    response = session.get("http://httpbin.org/ip", timeout=3)

    print(response.text)
```

Its how I make the modified the requests in the script

**Comment by ZigmundVonZaun** [comment]
is everythin ok on your side?

**Comment by hadi850085** [comment]
Hi, I want **xss scanner** to work with **tor** proxy, but I do not know how to connect to proxy?

**Pull request closed without merging**
